# Generated by Django 4.0.3 on 2022-04-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellidos_cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('correo_cliente', models.EmailField(max_length=50)),
                ('celular_cliente', models.CharField(max_length=10)),
                ('activo_cliente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_equipo', models.CharField(max_length=100)),
                ('marca_equipo', models.CharField(max_length=100)),
                ('num_serie_equipo', models.CharField(max_length=100)),
                ('num_parte_equipo', models.CharField(max_length=100)),
                ('procesador_equipo', models.CharField(max_length=100)),
                ('ram_equipo', models.CharField(max_length=100)),
                ('disco_equipo', models.CharField(max_length=100)),
                ('comentario_equipo', models.CharField(max_length=500)),
                ('activo_equipo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_producto', models.CharField(max_length=50)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.CharField(max_length=500)),
                ('activo_producto', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_servicio', models.CharField(max_length=50)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('descripcion_servicio', models.CharField(max_length=500)),
                ('activo_servicio', models.BooleanField(default=True)),
            ],
        ),
    ]
