# Generated by Django 4.0.3 on 2022-04-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('num_serie', models.CharField(max_length=100)),
                ('num_parte', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('disco', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=255)),
            ],
        ),
    ]
