# Generated by Django 4.0.3 on 2022-04-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_opr_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opr_solicitud',
            name='fecha_baja_solicitud',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opr_solicitud',
            name='fecha_entrega_solicitud',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opr_solicitud',
            name='fecha_estimada_entrega_solicitud',
            field=models.DateField(),
        ),
    ]
